version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 40s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ayu-network
    ports:
      - 3306:3306
  demogetir:
    container_name: demogetir
    image: ayu/demo-getir
    restart: unless-stopped
    networks:
      - ayu-network
    environment:
      MYSQL_IP: mysql
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
networks:
  getir-network:
    name: ayu-network
    driver: bridge